version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=nombre base de datos
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=contraseña
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
