version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=ocms
      - POSTGRES_USER=marcelo
      - POSTGRES_PASSWORD=1234
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql

volumes:
  postgresql-volume: 
    external: true
